services:
  clang:
    build:
      x-bake:
        platforms:
          - linux/amd64
    container_name: clang
    volumes:
      - ../../src:/opt/app/src:ro
      - ../../.build/clang:/opt/app/build
    command: ["/opt/app/src/main.cpp", "-o", "/opt/app/build/main"]